name: End-to-end tests
on:
  pull_request:
  
permissions:
  id-token: write
  pages: write
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: todomvc-typescript-react
          install-command: npm install
          build: npm run build
          start: npm start
      - name: Generate report
        if: always()
        run: cd todomvc-typescript-react && npm run cy:report
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-cucumber-report
          path: todomvc-typescript-react/cypress/cucumber-report/
     
